In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from numpy import load,save 
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (20,10)
plt.rcParams["figure.figsize"] = (20,10)

C:\Users\nmadhar\AppData\Roaming\Python\Python37\site-packages\pandas\compat\_optional.py:138: UserWarning: Pandas requires version '2.7.0' or newer of 'numexpr' (version '2.6.9' currently installed).
  warnings.warn(msg, UserWarning)

In [2]:
def ProcessingBoxPlot(Table):
    Train = Table.iloc[:,:4]
    Test = Table.iloc[:,4:]
    
    dfBox = pd.DataFrame(columns=['Scores','ScoreName','SetName'],dtype=float,index=np.arange(4*n*2))
    dfBox.loc[:4*n-1,'Scores'] = np.concatenate([Train.iloc[:,0],Train.iloc[:,1],
                                     Train.iloc[:,2],Train.iloc[:,3]])
    dfBox.loc[:4*n-1,'ScoreName'] = np.concatenate([['Accuracy']*n,['Precision']*n,
                                        ['Recall']*n,['F1Score']*n])
    dfBox.loc[:4*n-1,'SetName'] = ['Train']*4*n


    dfBox.loc[4*n:,'Scores'] = np.concatenate([Test.iloc[:,0],Test.iloc[:,1],
                                     Test.iloc[:,2],Test.iloc[:,3]])
    dfBox.loc[4*n:,'ScoreName'] = np.concatenate([['Accuracy']*n,['Precision']*n,
                                        ['Recall']*n,['F1Score']*n])
    dfBox.loc[4*n:,'SetName'] = ['Test']*4*n
    return dfBox


def PlotBoxplot(dfBox):
    plt.subplot(2,2,1)
    f1 = sns.boxplot(y='Scores', x='ScoreName', 
                     data=dfBox[dfBox['ScoreName']=='Accuracy'], 
                     palette="colorblind",
                     hue='SetName')
    f1.set(xlabel=None)
    plt.legend(fontsize=20)


    plt.subplot(2,2,2)
    f1 = sns.boxplot(y='Scores', x='ScoreName', 
                     data=dfBox[dfBox['ScoreName']=='Precision'], 
                     palette="colorblind",
                     hue='SetName')
    f1.set(xlabel=None)
    plt.legend(fontsize=20)


    plt.subplot(2,2,3)
    f1 = sns.boxplot(y='Scores', x='ScoreName', 
                     data=dfBox[dfBox['ScoreName']=='Recall'], 
                     palette="colorblind",
                     hue='SetName')
    f1.set(xlabel=None)
    plt.legend(fontsize=20)


    plt.subplot(2,2,4)
    f1 = sns.boxplot(y='Scores', x='ScoreName', 
                     data=dfBox[dfBox['ScoreName']=='F1Score'], 
                     palette="colorblind",
                     hue='SetName')
    f1.set(xlabel=None)
    plt.legend(fontsize=20)


    plt.show()

In [3]:
ResTableIdentification = pd.read_csv(r'C:\Users\nmadhar\Desktop\Conv_deep\ToSubmit\Results\StabilityTables\StabilityCheckResIdentificationModel.csv').drop('Unnamed: 0',axis=1)
n,d = ResTableIdentification.shape



ResTableLocationDummy = load(r'C:\Users\nmadhar\Desktop\Conv_deep\ToSubmit\Results\StabilityTables\ResTableLocationDummyModel_all.pkl',allow_pickle=True)
ResTableLocation = load(r'C:\Users\nmadhar\Desktop\Conv_deep\ToSubmit\Results\StabilityTables\ResTableLocationModel_all.pkl',allow_pickle=True)

resLocAllAnomaly = ResTableLocation['All Anomaly']
resLocNEAnomaly = ResTableLocation['Anomaly NE']


resLocAllAnomalyDummy  = ResTableLocationDummy ['All Anomaly']
resLocNEAnomalyDummy  = ResTableLocationDummy ['Anomaly NE']

In [4]:
dfBoxIndentification =  ProcessingBoxPlot(ResTableIdentification)
dfBoxLocAllAnomaly = ProcessingBoxPlot(resLocAllAnomaly)
dfBoxLocNEAnomaly = ProcessingBoxPlot(resLocNEAnomaly)

In [5]:
dfBoxIndentification.groupby(['ScoreName','SetName']).mean()

                     Scores
ScoreName SetName
Accuracy  Test     0.777854
          Train    0.790218
F1Score   Test     0.548247
          Train    0.791310
Precision Test     0.418688
          Train    0.786891
Recall    Test     0.801563
          Train    0.797484

In [6]:
dfBoxIndentification.groupby(['ScoreName','SetName']).std()

                     Scores
ScoreName SetName
Accuracy  Test     0.039028
          Train    0.024238
F1Score   Test     0.052120
          Train    0.026916
Precision Test     0.051983
          Train    0.026565
Recall    Test     0.064151
          Train    0.045583

In [7]:
dfBoxLocAllAnomaly.groupby(['ScoreName','SetName']).mean()

                     Scores
ScoreName SetName
Accuracy  Test     0.894887
          Train    0.895846
F1Score   Test     0.895821
          Train    0.896661
Precision Test     0.894887
          Train    0.895846
Recall    Test     0.900099
          Train    0.899569

In [8]:
dfBoxLocAllAnomaly.groupby(['ScoreName','SetName']).std()

                     Scores
ScoreName SetName
Accuracy  Test     0.047800
          Train    0.043391
F1Score   Test     0.047211
          Train    0.042819
Precision Test     0.047800
          Train    0.043391
Recall    Test     0.045065
          Train    0.041231

In [9]:
dfBoxLocNEAnomaly.groupby(['ScoreName','SetName']).mean()

                     Scores
ScoreName SetName
Accuracy  Test     0.851674
          Train    0.852338
F1Score   Test     0.852984
          Train    0.853613
Precision Test     0.851674
          Train    0.852338
Recall    Test     0.860404
          Train    0.858694

In [10]:
dfBoxLocNEAnomaly.groupby(['ScoreName','SetName']).std()

                     Scores
ScoreName SetName
Accuracy  Test     0.071371
          Train    0.060305
F1Score   Test     0.071002
          Train    0.059511
Precision Test     0.071371
          Train    0.060305
Recall    Test     0.068124
          Train    0.057028